/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Jet.glb -o src/components/Jet.jsx -r public -k
*/

import { useRef, useEffect, useState, useLayoutEffect } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";

gsap.registerPlugin(useGSAP, ScrollTrigger);

export function Jet(props) {
  const { nodes, materials } = useGLTF("/models/Jet.glb");
  const [isHovered, setIsHovered] = useState(false);
  const [name, setName] = useState([]);
  const group = useRef();
  const originalPositions = useRef({});
  const currentOffsets = useRef({});

  useGSAP(() => {
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: ".batas",
        start: "top bottom",
        end: "top center",
        scrub: true,
        // markers: true,
      },
    });

    tl.to(group.current.scale, { x: 0.06, y: 0.06, z: 0.06, ease: "slow(0.5, 0.8, true)" })
      .to(
        group.current.position,
        {
          x: 3.1,
          y: -1.4,
          duration: 2,
          ease: "slow(0.5, 0.8, true)",
        },
        "<"
      )
      .to(group.current.rotation, {
        y: -2.3,
        x: 0.6,
        z: 0.2,
        duration: 2,
        ease: "slow(0.5, 0.8, true)",
      });
  });

  useEffect(() => {
    group.current.children.forEach((mesh) => {
      originalPositions.current[mesh.uuid] = mesh.position.clone();
      currentOffsets.current[mesh.uuid] = new THREE.Vector3();
    });
  }, []);

  useFrame((state, delta) => {
    const time = state.clock.getElapsedTime();

    group.current.children.forEach((mesh) => {
      const originalPos = originalPositions.current[mesh.uuid];
      const currentOffset = currentOffsets.current[mesh.uuid];
      if (isHovered && mesh.name === name) {
        const targetOffset = new THREE.Vector3(Math.sin(time * 1.5) * 0.05, originalPos.y - Math.abs(Math.sin(state.clock.elapsedTime * 2)) * 8, Math.cos(time * 1.5) * 0.05);

        currentOffset.lerp(targetOffset, 0.25);
      } else {
        currentOffset.lerp(new THREE.Vector3(0, 0, 0), 0.05);
      }
      mesh.position.copy(originalPos).add(currentOffset);
    });
  });

  function handlePointerEnter(name) {
    setIsHovered(true);
    setName(name);
  }

  function handlePointerLeave() {
    setIsHovered(false);
    setName("");
  }

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        className="box"
        name="Cube"
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[18.633, 0.967, -0.991]}
      />
      <mesh
        className="box"
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[18.633, 0.967, 1.059]}
      />
      <mesh
        className="box"
        name="Cube002"
        geometry={nodes.Cube002.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[16.598, 0.967, -0.988]}
      />
      <mesh
        className="box"
        name="Cube003"
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[16.598, 0.967, 1.087]}
      />
      <mesh
        className="box"
        name="Cube004"
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[14.567, 0.967, 1.087]}
      />
      <mesh
        className="box"
        name="Cube005"
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[14.567, 0.967, -1.019]}
      />
      <mesh
        className="box"
        name="Cube006"
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[12.554, 0.967, 1.087]}
      />
      <mesh
        className="box"
        name="Cube007"
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[12.554, 0.967, -1.046]}
      />
      <mesh
        className="box"
        name="Cube008"
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[12.554, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube009"
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[12.554, 0.967, -3.066]}
      />
      <mesh
        className="box"
        name="Cube010"
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[12.554, 3.032, 1.053]}
      />
      <mesh
        className="box"
        name="Cube011"
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[12.554, 3.055, -1.02]}
      />
      <mesh
        className="box"
        name="Cube012"
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube013"
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 0.967, 1.073]}
      />
      <mesh
        className="box"
        name="Cube014"
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 0.967, -1.024]}
      />
      <mesh
        className="box"
        name="Cube015"
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 0.967, -3.069]}
      />
      <mesh
        className="box"
        name="Cube016"
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 3.019, -3.069]}
      />
      <mesh
        className="box"
        name="Cube017"
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 3.019, -0.975]}
      />
      <mesh
        className="box"
        name="Cube018"
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 3.019, 1.094]}
      />
      <mesh
        className="box"
        name="Cube019"
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[10.476, 3.019, 3.138]}
      />
      <mesh
        className="box"
        name="Cube020"
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube021"
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube022"
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube023"
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube024"
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube025"
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube026"
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube027"
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[8.371, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube035"
        geometry={nodes.Cube035.geometry}
        material={nodes.Cube035.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube034"
        geometry={nodes.Cube034.geometry}
        material={nodes.Cube034.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube033"
        geometry={nodes.Cube033.geometry}
        material={nodes.Cube033.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube032"
        geometry={nodes.Cube032.geometry}
        material={nodes.Cube032.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube031"
        geometry={nodes.Cube031.geometry}
        material={nodes.Cube031.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube030"
        geometry={nodes.Cube030.geometry}
        material={nodes.Cube030.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube029"
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube028"
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube038"
        geometry={nodes.Cube038.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube037"
        geometry={nodes.Cube037.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube047"
        geometry={nodes.Cube047.geometry}
        material={nodes.Cube047.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube046"
        geometry={nodes.Cube046.geometry}
        material={nodes.Cube046.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube045"
        geometry={nodes.Cube045.geometry}
        material={nodes.Cube045.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube044"
        geometry={nodes.Cube044.geometry}
        material={nodes.Cube044.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube043"
        geometry={nodes.Cube043.geometry}
        material={nodes.Cube043.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube042"
        geometry={nodes.Cube042.geometry}
        material={nodes.Cube042.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube041"
        geometry={nodes.Cube041.geometry}
        material={nodes.Cube041.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube040"
        geometry={nodes.Cube040.geometry}
        material={nodes.Cube040.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube039"
        geometry={nodes.Cube039.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube036"
        geometry={nodes.Cube036.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube057"
        geometry={nodes.Cube057.geometry}
        material={nodes.Cube057.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube056"
        geometry={nodes.Cube056.geometry}
        material={nodes.Cube056.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube055"
        geometry={nodes.Cube055.geometry}
        material={nodes.Cube055.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube054"
        geometry={nodes.Cube054.geometry}
        material={nodes.Cube054.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube053"
        geometry={nodes.Cube053.geometry}
        material={nodes.Cube053.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube052"
        geometry={nodes.Cube052.geometry}
        material={nodes.Cube052.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube051"
        geometry={nodes.Cube051.geometry}
        material={nodes.Cube051.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube050"
        geometry={nodes.Cube050.geometry}
        material={nodes.Cube050.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube049"
        geometry={nodes.Cube049.geometry}
        material={nodes.Cube049.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube048"
        geometry={nodes.Cube048.geometry}
        material={nodes.Cube048.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube067"
        geometry={nodes.Cube067.geometry}
        material={nodes.Cube067.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube066"
        geometry={nodes.Cube066.geometry}
        material={nodes.Cube066.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube065"
        geometry={nodes.Cube065.geometry}
        material={nodes.Cube065.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube064"
        geometry={nodes.Cube064.geometry}
        material={nodes.Cube064.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube063"
        geometry={nodes.Cube063.geometry}
        material={nodes.Cube063.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube062"
        geometry={nodes.Cube062.geometry}
        material={nodes.Cube062.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube061"
        geometry={nodes.Cube061.geometry}
        material={nodes.Cube061.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube060"
        geometry={nodes.Cube060.geometry}
        material={nodes.Cube060.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube059"
        geometry={nodes.Cube059.geometry}
        material={nodes.Cube059.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube058"
        geometry={nodes.Cube058.geometry}
        material={nodes.Cube058.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube077"
        geometry={nodes.Cube077.geometry}
        material={nodes.Cube077.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube076"
        geometry={nodes.Cube076.geometry}
        material={nodes.Cube076.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube075"
        geometry={nodes.Cube075.geometry}
        material={nodes.Cube075.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube074"
        geometry={nodes.Cube074.geometry}
        material={nodes.Cube074.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube073"
        geometry={nodes.Cube073.geometry}
        material={nodes.Cube073.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube072"
        geometry={nodes.Cube072.geometry}
        material={nodes.Cube072.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube071"
        geometry={nodes.Cube071.geometry}
        material={nodes.Cube071.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube070"
        geometry={nodes.Cube070.geometry}
        material={nodes.Cube070.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube069"
        geometry={nodes.Cube069.geometry}
        material={nodes.Cube069.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube068"
        geometry={nodes.Cube068.geometry}
        material={nodes.Cube068.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube087"
        geometry={nodes.Cube087.geometry}
        material={nodes.Cube087.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube086"
        geometry={nodes.Cube086.geometry}
        material={nodes.Cube086.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube085"
        geometry={nodes.Cube085.geometry}
        material={nodes.Cube085.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube084"
        geometry={nodes.Cube084.geometry}
        material={nodes.Cube084.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube083"
        geometry={nodes.Cube083.geometry}
        material={nodes.Cube083.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube082"
        geometry={nodes.Cube082.geometry}
        material={nodes.Cube082.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube081"
        geometry={nodes.Cube081.geometry}
        material={nodes.Cube081.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube080"
        geometry={nodes.Cube080.geometry}
        material={nodes.Cube080.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube079"
        geometry={nodes.Cube079.geometry}
        material={nodes.Cube079.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube078"
        geometry={nodes.Cube078.geometry}
        material={nodes.Cube078.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube097"
        geometry={nodes.Cube097.geometry}
        material={nodes.Cube097.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube096"
        geometry={nodes.Cube096.geometry}
        material={nodes.Cube096.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube095"
        geometry={nodes.Cube095.geometry}
        material={nodes.Cube095.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube094"
        geometry={nodes.Cube094.geometry}
        material={nodes.Cube094.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube093"
        geometry={nodes.Cube093.geometry}
        material={nodes.Cube093.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube092"
        geometry={nodes.Cube092.geometry}
        material={nodes.Cube092.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube091"
        geometry={nodes.Cube091.geometry}
        material={nodes.Cube091.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube090"
        geometry={nodes.Cube090.geometry}
        material={nodes.Cube090.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube089"
        geometry={nodes.Cube089.geometry}
        material={nodes.Cube089.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube088"
        geometry={nodes.Cube088.geometry}
        material={nodes.Cube088.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube107"
        geometry={nodes.Cube107.geometry}
        material={nodes.Cube107.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube106"
        geometry={nodes.Cube106.geometry}
        material={nodes.Cube106.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube105"
        geometry={nodes.Cube105.geometry}
        material={nodes.Cube105.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube104"
        geometry={nodes.Cube104.geometry}
        material={nodes.Cube104.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube103"
        geometry={nodes.Cube103.geometry}
        material={nodes.Cube103.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube102"
        geometry={nodes.Cube102.geometry}
        material={nodes.Cube102.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube101"
        geometry={nodes.Cube101.geometry}
        material={nodes.Cube101.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube100"
        geometry={nodes.Cube100.geometry}
        material={nodes.Cube100.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube099"
        geometry={nodes.Cube099.geometry}
        material={nodes.Cube099.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube098"
        geometry={nodes.Cube098.geometry}
        material={nodes.Cube098.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube117"
        geometry={nodes.Cube117.geometry}
        material={nodes.Cube117.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube116"
        geometry={nodes.Cube116.geometry}
        material={nodes.Cube116.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube115"
        geometry={nodes.Cube115.geometry}
        material={nodes.Cube115.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube114"
        geometry={nodes.Cube114.geometry}
        material={nodes.Cube114.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube113"
        geometry={nodes.Cube113.geometry}
        material={nodes.Cube113.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube112"
        geometry={nodes.Cube112.geometry}
        material={nodes.Cube112.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube111"
        geometry={nodes.Cube111.geometry}
        material={nodes.Cube111.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube110"
        geometry={nodes.Cube110.geometry}
        material={nodes.Cube110.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube109"
        geometry={nodes.Cube109.geometry}
        material={nodes.Cube109.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube108"
        geometry={nodes.Cube108.geometry}
        material={nodes.Cube108.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube127"
        geometry={nodes.Cube127.geometry}
        material={nodes.Cube127.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 3.019, -3.034]}
      />
      <mesh
        className="box"
        name="Cube126"
        geometry={nodes.Cube126.geometry}
        material={nodes.Cube126.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, -3.034]}
      />
      <mesh
        className="box"
        name="Cube125"
        geometry={nodes.Cube125.geometry}
        material={nodes.Cube125.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube124"
        geometry={nodes.Cube124.geometry}
        material={nodes.Cube124.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube123"
        geometry={nodes.Cube123.geometry}
        material={nodes.Cube123.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube122"
        geometry={nodes.Cube122.geometry}
        material={nodes.Cube122.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube121"
        geometry={nodes.Cube121.geometry}
        material={nodes.Cube121.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 3.022, 3.134]}
      />
      <mesh
        className="box"
        name="Cube120"
        geometry={nodes.Cube120.geometry}
        material={nodes.Cube120.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 3.134]}
      />
      <mesh
        className="box"
        name="Cube119"
        geometry={nodes.Cube119.geometry}
        material={nodes.Cube119.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube118"
        geometry={nodes.Cube118.geometry}
        material={nodes.Cube118.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube137"
        geometry={nodes.Cube137.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.149, 5.046, -0.965]}
      />
      <mesh
        className="box"
        name="Cube136"
        geometry={nodes.Cube136.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.149, 5.047, 1.109]}
      />
      <mesh
        className="box"
        name="Cube133"
        geometry={nodes.Cube133.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.149, 0.967, 1.109]}
      />
      <mesh
        className="box"
        name="Cube132"
        geometry={nodes.Cube132.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.149, 3.016, 1.109]}
      />
      <mesh
        className="box"
        name="Cube131"
        geometry={nodes.Cube131.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.149, 3.015, -0.965]}
      />
      <mesh
        className="box"
        name="Cube130"
        geometry={nodes.Cube130.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.149, 0.967, -0.884]}
      />
      <mesh
        className="box"
        name="Cube128"
        geometry={nodes.Cube128.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 5.046, -3.114]}
      />
      <mesh
        className="box"
        name="Cube129"
        geometry={nodes.Cube129.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.243, 5.046, -3.114]}
      />
      <mesh
        className="box"
        name="Cube134"
        geometry={nodes.Cube134.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 5.047, 3.236]}
      />
      <mesh
        className="box"
        name="Cube135"
        geometry={nodes.Cube135.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.212, 5.047, 3.236]}
      />
      <mesh
        className="box"
        name="Cube141"
        geometry={nodes.Cube141.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 7.111, 1.109]}
      />
      <mesh
        className="box"
        name="Cube140"
        geometry={nodes.Cube140.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 7.109, -0.965]}
      />
      <mesh
        className="box"
        name="Cube139"
        geometry={nodes.Cube139.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 7.109, -0.965]}
      />
      <mesh
        className="box"
        name="Cube138"
        geometry={nodes.Cube138.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 7.111, 1.109]}
      />
      <mesh
        className="box"
        name="Cube145"
        geometry={nodes.Cube145.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.103, 7.111, 1.067]}
      />
      <mesh
        className="box"
        name="Cube144"
        geometry={nodes.Cube144.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.103, 7.109, -1.007]}
      />
      <mesh
        className="box"
        name="Cube143"
        geometry={nodes.Cube143.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.025, 7.109, -1.007]}
      />
      <mesh
        className="box"
        name="Cube142"
        geometry={nodes.Cube142.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.025, 7.111, 1.067]}
      />
      <mesh
        className="box"
        name="Cube147"
        geometry={nodes.Cube147.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.103, 9.109, -1.007]}
      />
      <mesh
        className="box"
        name="Cube146"
        geometry={nodes.Cube146.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-12.103, 9.111, 1.067]}
      />
      <mesh
        className="box"
        name="Cube156"
        geometry={nodes.Cube156.geometry}
        material={nodes.Cube156.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube155"
        geometry={nodes.Cube155.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube154"
        geometry={nodes.Cube154.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube153"
        geometry={nodes.Cube153.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube152"
        geometry={nodes.Cube152.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube151"
        geometry={nodes.Cube151.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube150"
        geometry={nodes.Cube150.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube149"
        geometry={nodes.Cube149.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube148"
        geometry={nodes.Cube148.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 5.294]}
      />
      <mesh
        className="box"
        name="Cube164"
        geometry={nodes.Cube164.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube163"
        geometry={nodes.Cube163.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube162"
        geometry={nodes.Cube162.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube161"
        geometry={nodes.Cube161.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube160"
        geometry={nodes.Cube160.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube159"
        geometry={nodes.Cube159.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube158"
        geometry={nodes.Cube158.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube157"
        geometry={nodes.Cube157.geometry}
        material={nodes.Cube157.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.967, 7.318]}
      />
      <mesh
        className="box"
        name="Cube172"
        geometry={nodes.Cube172.geometry}
        material={nodes.Cube172.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube171"
        geometry={nodes.Cube171.geometry}
        material={nodes.Cube171.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube170"
        geometry={nodes.Cube170.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube169"
        geometry={nodes.Cube169.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube168"
        geometry={nodes.Cube168.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube167"
        geometry={nodes.Cube167.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube166"
        geometry={nodes.Cube166.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube165"
        geometry={nodes.Cube165.geometry}
        material={nodes.Cube165.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 9.364]}
      />
      <mesh
        className="box"
        name="Cube173"
        geometry={nodes.Cube173.geometry}
        material={nodes.Cube173.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.967, 9.331]}
      />
      <mesh
        className="box"
        name="Cube179"
        geometry={nodes.Cube179.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 11.387]}
      />
      <mesh
        className="box"
        name="Cube178"
        geometry={nodes.Cube178.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 11.387]}
      />
      <mesh
        className="box"
        name="Cube177"
        geometry={nodes.Cube177.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 11.387]}
      />
      <mesh
        className="box"
        name="Cube176"
        geometry={nodes.Cube176.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, 11.387]}
      />
      <mesh
        className="box"
        name="Cube175"
        geometry={nodes.Cube175.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.967, 11.387]}
      />
      <mesh
        className="box"
        name="Cube174"
        geometry={nodes.Cube174.geometry}
        material={nodes.Cube174.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.967, 11.387]}
      />
      <mesh
        className="box"
        name="Cube183"
        geometry={nodes.Cube183.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.967, 13.48]}
      />
      <mesh
        className="box"
        name="Cube182"
        geometry={nodes.Cube182.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 13.48]}
      />
      <mesh
        className="box"
        name="Cube181"
        geometry={nodes.Cube181.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 13.48]}
      />
      <mesh
        className="box"
        name="Cube180"
        geometry={nodes.Cube180.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 13.48]}
      />
      <mesh
        className="box"
        name="Cube186"
        geometry={nodes.Cube186.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 15.582]}
      />
      <mesh
        className="box"
        name="Cube185"
        geometry={nodes.Cube185.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 15.582]}
      />
      <mesh
        className="box"
        name="Cube184"
        geometry={nodes.Cube184.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 15.582]}
      />
      <mesh
        className="box"
        name="Cube189"
        geometry={nodes.Cube189.geometry}
        material={nodes.Cube189.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.967, 17.59]}
      />
      <mesh
        className="box"
        name="Cube188"
        geometry={nodes.Cube188.geometry}
        material={nodes.Cube188.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.967, 17.59]}
      />
      <mesh
        className="box"
        name="Cube187"
        geometry={nodes.Cube187.geometry}
        material={nodes.Cube187.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.967, 17.59]}
      />
      <mesh
        className="box"
        name="Cube190"
        geometry={nodes.Cube190.geometry}
        material={nodes.Cube190.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.934, 0.967, 17.59]}
      />
      <mesh
        className="box"
        name="Cube191"
        geometry={nodes.Cube191.geometry}
        material={nodes.Cube191.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.899, 0.967, 17.59]}
      />
      <mesh
        className="box"
        name="Cube235"
        geometry={nodes.Cube235.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube234"
        geometry={nodes.Cube234.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube233"
        geometry={nodes.Cube233.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube232"
        geometry={nodes.Cube232.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube231"
        geometry={nodes.Cube231.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube230"
        geometry={nodes.Cube230.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube229"
        geometry={nodes.Cube229.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube228"
        geometry={nodes.Cube228.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube227"
        geometry={nodes.Cube227.geometry}
        material={nodes.Cube227.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.946, -5.035]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube226"
        geometry={nodes.Cube226.geometry}
        material={nodes.Cube226.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube225"
        geometry={nodes.Cube225.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube224"
        geometry={nodes.Cube224.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube223"
        geometry={nodes.Cube223.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube222"
        geometry={nodes.Cube222.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube221"
        geometry={nodes.Cube221.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube220"
        geometry={nodes.Cube220.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube219"
        geometry={nodes.Cube219.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.955, -7.058]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube218"
        geometry={nodes.Cube218.geometry}
        material={nodes.Cube218.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube217"
        geometry={nodes.Cube217.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube216"
        geometry={nodes.Cube216.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube215"
        geometry={nodes.Cube215.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube214"
        geometry={nodes.Cube214.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube213"
        geometry={nodes.Cube213.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube212"
        geometry={nodes.Cube212.geometry}
        material={nodes.Cube212.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[2.245, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube211"
        geometry={nodes.Cube211.geometry}
        material={nodes.Cube211.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[4.269, 0.964, -9.104]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube210"
        geometry={nodes.Cube210.geometry}
        material={nodes.Cube210.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[6.326, 0.963, -9.071]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube209"
        geometry={nodes.Cube209.geometry}
        material={nodes.Cube209.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[0.206, 0.972, -11.127]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube208"
        geometry={nodes.Cube208.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.825, 0.972, -11.127]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube207"
        geometry={nodes.Cube207.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.972, -11.127]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube206"
        geometry={nodes.Cube206.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.972, -11.127]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube205"
        geometry={nodes.Cube205.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.972, -11.127]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube204"
        geometry={nodes.Cube204.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.972, -11.127]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube203"
        geometry={nodes.Cube203.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.981, -13.22]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube202"
        geometry={nodes.Cube202.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.981, -13.22]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube201"
        geometry={nodes.Cube201.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.981, -13.22]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube200"
        geometry={nodes.Cube200.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.942, 0.981, -13.22]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube199"
        geometry={nodes.Cube199.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.99, -15.322]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube198"
        geometry={nodes.Cube198.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.99, -15.322]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube197"
        geometry={nodes.Cube197.geometry}
        material={materials["Material.001"]}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.99, -15.322]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube196"
        geometry={nodes.Cube196.geometry}
        material={nodes.Cube196.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-10.135, 0.999, -17.33]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube195"
        geometry={nodes.Cube195.geometry}
        material={nodes.Cube195.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-8.057, 0.999, -17.33]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube194"
        geometry={nodes.Cube194.geometry}
        material={nodes.Cube194.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-6.007, 0.999, -17.33]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube193"
        geometry={nodes.Cube193.geometry}
        material={nodes.Cube193.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-3.934, 0.999, -17.33]}
        rotation={[-3.137, 0, 0]}
      />
      <mesh
        className="box"
        name="Cube192"
        geometry={nodes.Cube192.geometry}
        material={nodes.Cube192.material}
        onPointerEnter={(e) => handlePointerEnter(e.eventObject.name)}
        onPointerLeave={() => handlePointerLeave()}
        position={[-1.899, 0.999, -17.33]}
        rotation={[-3.137, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/Jet.glb");
